// Generated by `supabase gen types typescript`. Do not edit by hand.
//
// Provenance: generated from supabase/schema.sql + every file in
// supabase/migrations/ applied in order to a disposable local Postgres, because
// generating from the hosted project needs the project owner's `supabase login`
// (see Makefile `gen-types`). Regenerate with `make gen-types` once the
// migrations are pushed, and this file should come back byte-identical apart
// from anything applied to the hosted DB outside of migrations/.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      action_evidence: {
        Row: {
          action_id: number
          captured_at: string
          captured_by: string | null
          created_at: string
          evidence_type: string
          id: number
          is_offline_capture: boolean
          payload: Json
          photo_url: string | null
          synced_at: string | null
        }
        Insert: {
          action_id: number
          captured_at?: string
          captured_by?: string | null
          created_at?: string
          evidence_type: string
          id?: number
          is_offline_capture?: boolean
          payload?: Json
          photo_url?: string | null
          synced_at?: string | null
        }
        Update: {
          action_id?: number
          captured_at?: string
          captured_by?: string | null
          created_at?: string
          evidence_type?: string
          id?: number
          is_offline_capture?: boolean
          payload?: Json
          photo_url?: string | null
          synced_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "action_evidence_action_id_fkey"
            columns: ["action_id"]
            isOneToOne: false
            referencedRelation: "actions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_evidence_captured_by_fkey"
            columns: ["captured_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      actions: {
        Row: {
          accepted_at: string | null
          approval_level: Database["public"]["Enums"]["approval_level"] | null
          approved_at: string | null
          approved_by: string | null
          assigned_to: string | null
          checklist_snapshot: Json | null
          completed_at: string | null
          created_at: string | null
          custom_reason: string | null
          deadline: string | null
          evidence: Json | null
          expected_verification_hours: number | null
          id: number
          incident_id: number | null
          not_completed_reason: string | null
          playbook_id: number | null
          playbook_notes_override: string | null
          playbook_version: number | null
          priority_score: number | null
          proof_url: string | null
          recommended_action: string | null
          report_id: number | null
          resolved_at: string | null
          responsible_agency: string | null
          source_confirmed: boolean | null
          started_at: string | null
          status: Database["public"]["Enums"]["report_status"]
          type: string | null
          ward_id: number
          workflow_status: Database["public"]["Enums"]["action_workflow_status"]
        }
        Insert: {
          accepted_at?: string | null
          approval_level?: Database["public"]["Enums"]["approval_level"] | null
          approved_at?: string | null
          approved_by?: string | null
          assigned_to?: string | null
          checklist_snapshot?: Json | null
          completed_at?: string | null
          created_at?: string | null
          custom_reason?: string | null
          deadline?: string | null
          evidence?: Json | null
          expected_verification_hours?: number | null
          id?: number
          incident_id?: number | null
          not_completed_reason?: string | null
          playbook_id?: number | null
          playbook_notes_override?: string | null
          playbook_version?: number | null
          priority_score?: number | null
          proof_url?: string | null
          recommended_action?: string | null
          report_id?: number | null
          resolved_at?: string | null
          responsible_agency?: string | null
          source_confirmed?: boolean | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          type?: string | null
          ward_id: number
          workflow_status?: Database["public"]["Enums"]["action_workflow_status"]
        }
        Update: {
          accepted_at?: string | null
          approval_level?: Database["public"]["Enums"]["approval_level"] | null
          approved_at?: string | null
          approved_by?: string | null
          assigned_to?: string | null
          checklist_snapshot?: Json | null
          completed_at?: string | null
          created_at?: string | null
          custom_reason?: string | null
          deadline?: string | null
          evidence?: Json | null
          expected_verification_hours?: number | null
          id?: number
          incident_id?: number | null
          not_completed_reason?: string | null
          playbook_id?: number | null
          playbook_notes_override?: string | null
          playbook_version?: number | null
          priority_score?: number | null
          proof_url?: string | null
          recommended_action?: string | null
          report_id?: number | null
          resolved_at?: string | null
          responsible_agency?: string | null
          source_confirmed?: boolean | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          type?: string | null
          ward_id?: number
          workflow_status?: Database["public"]["Enums"]["action_workflow_status"]
        }
        Relationships: [
          {
            foreignKeyName: "actions_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "actions_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "actions_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "actions_playbook_id_fkey"
            columns: ["playbook_id"]
            isOneToOne: false
            referencedRelation: "intervention_playbooks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "actions_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "actions_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      anomaly_candidates: {
        Row: {
          baseline_value: number | null
          city_id: number | null
          confidence: number | null
          created_at: string
          current_concentration: number | null
          data_completeness: number | null
          data_freshness_minutes: number | null
          detected_at: string
          detection_stage:
            | Database["public"]["Enums"]["incident_detection_stage"]
            | null
          id: number
          incident_id: number | null
          local_excess: number | null
          nearby_station_diff: number | null
          persistence_count: number | null
          pollutant: string
          prediction_method: string | null
          projected_crossing_at: string | null
          rate_of_increase: number | null
          sensor_quality: string | null
          station_id: number | null
          suppressed: boolean
          suppression_reason: string | null
          threshold_crossing_probability: number | null
          threshold_used: number | null
          triggered_rules: Json
          ward_id: number | null
        }
        Insert: {
          baseline_value?: number | null
          city_id?: number | null
          confidence?: number | null
          created_at?: string
          current_concentration?: number | null
          data_completeness?: number | null
          data_freshness_minutes?: number | null
          detected_at?: string
          detection_stage?:
            | Database["public"]["Enums"]["incident_detection_stage"]
            | null
          id?: number
          incident_id?: number | null
          local_excess?: number | null
          nearby_station_diff?: number | null
          persistence_count?: number | null
          pollutant: string
          prediction_method?: string | null
          projected_crossing_at?: string | null
          rate_of_increase?: number | null
          sensor_quality?: string | null
          station_id?: number | null
          suppressed?: boolean
          suppression_reason?: string | null
          threshold_crossing_probability?: number | null
          threshold_used?: number | null
          triggered_rules?: Json
          ward_id?: number | null
        }
        Update: {
          baseline_value?: number | null
          city_id?: number | null
          confidence?: number | null
          created_at?: string
          current_concentration?: number | null
          data_completeness?: number | null
          data_freshness_minutes?: number | null
          detected_at?: string
          detection_stage?:
            | Database["public"]["Enums"]["incident_detection_stage"]
            | null
          id?: number
          incident_id?: number | null
          local_excess?: number | null
          nearby_station_diff?: number | null
          persistence_count?: number | null
          pollutant?: string
          prediction_method?: string | null
          projected_crossing_at?: string | null
          rate_of_increase?: number | null
          sensor_quality?: string | null
          station_id?: number | null
          suppressed?: boolean
          suppression_reason?: string | null
          threshold_crossing_probability?: number | null
          threshold_used?: number | null
          triggered_rules?: Json
          ward_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "anomaly_candidates_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "city_config"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "anomaly_candidates_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "anomaly_candidates_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "anomaly_candidates_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      attributions: {
        Row: {
          breakdown: Json | null
          confidence: number | null
          direction: string | null
          id: number
          method: string | null
          ts: string
          ward_id: number
        }
        Insert: {
          breakdown?: Json | null
          confidence?: number | null
          direction?: string | null
          id?: number
          method?: string | null
          ts?: string
          ward_id: number
        }
        Update: {
          breakdown?: Json | null
          confidence?: number | null
          direction?: string | null
          id?: number
          method?: string | null
          ts?: string
          ward_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "attributions_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      city_config: {
        Row: {
          city_code: string
          config: Json
          country: string
          created_at: string
          default_language: string
          id: number
          is_active: boolean
          name: string
          pollutant_priority: string[]
          supported_languages: string[]
          timezone: string
          updated_at: string
        }
        Insert: {
          city_code: string
          config?: Json
          country?: string
          created_at?: string
          default_language?: string
          id?: number
          is_active?: boolean
          name: string
          pollutant_priority?: string[]
          supported_languages?: string[]
          timezone?: string
          updated_at?: string
        }
        Update: {
          city_code?: string
          config?: Json
          country?: string
          created_at?: string
          default_language?: string
          id?: number
          is_active?: boolean
          name?: string
          pollutant_priority?: string[]
          supported_languages?: string[]
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      city_connectors: {
        Row: {
          city_id: number
          config: Json
          connector_type: string
          created_at: string
          id: number
          is_enabled: boolean
          last_sync_at: string | null
          last_sync_status: string | null
          provider: string
        }
        Insert: {
          city_id: number
          config?: Json
          connector_type: string
          created_at?: string
          id?: number
          is_enabled?: boolean
          last_sync_at?: string | null
          last_sync_status?: string | null
          provider: string
        }
        Update: {
          city_id?: number
          config?: Json
          connector_type?: string
          created_at?: string
          id?: number
          is_enabled?: boolean
          last_sync_at?: string | null
          last_sync_status?: string | null
          provider?: string
        }
        Relationships: [
          {
            foreignKeyName: "city_connectors_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "city_config"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_missions: {
        Row: {
          assigned_to: string | null
          checklist_response: Json | null
          completed_at: string | null
          created_at: string
          dispatched_at: string | null
          expected_confidence_gain: number | null
          id: number
          incident_id: number
          lat: number | null
          lng: number | null
          mission_type: string
          notes: string | null
          outcome: string | null
          proof_photo_url: string | null
          public_prompt: string | null
          rationale: string | null
          result: Json | null
          status: Database["public"]["Enums"]["mission_status"]
        }
        Insert: {
          assigned_to?: string | null
          checklist_response?: Json | null
          completed_at?: string | null
          created_at?: string
          dispatched_at?: string | null
          expected_confidence_gain?: number | null
          id?: number
          incident_id: number
          lat?: number | null
          lng?: number | null
          mission_type: string
          notes?: string | null
          outcome?: string | null
          proof_photo_url?: string | null
          public_prompt?: string | null
          rationale?: string | null
          result?: Json | null
          status?: Database["public"]["Enums"]["mission_status"]
        }
        Update: {
          assigned_to?: string | null
          checklist_response?: Json | null
          completed_at?: string | null
          created_at?: string
          dispatched_at?: string | null
          expected_confidence_gain?: number | null
          id?: number
          incident_id?: number
          lat?: number | null
          lng?: number | null
          mission_type?: string
          notes?: string | null
          outcome?: string | null
          proof_photo_url?: string | null
          public_prompt?: string | null
          rationale?: string | null
          result?: Json | null
          status?: Database["public"]["Enums"]["mission_status"]
        }
        Relationships: [
          {
            foreignKeyName: "evidence_missions_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_missions_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
        ]
      }
      forecast_runs: {
        Row: {
          beats_persistence: boolean
          city_id: number | null
          created_at: string
          data_completeness: number | null
          data_quality_status: string
          generated_at: string
          id: number
          max_validated_horizon_hours: number | null
          method: string
          model_version: string
          pollutant: string
          training_period_end: string | null
          training_period_start: string | null
          training_rows: number | null
          validation_metrics: Json
          ward_id: number
        }
        Insert: {
          beats_persistence?: boolean
          city_id?: number | null
          created_at?: string
          data_completeness?: number | null
          data_quality_status?: string
          generated_at?: string
          id?: number
          max_validated_horizon_hours?: number | null
          method: string
          model_version: string
          pollutant: string
          training_period_end?: string | null
          training_period_start?: string | null
          training_rows?: number | null
          validation_metrics?: Json
          ward_id: number
        }
        Update: {
          beats_persistence?: boolean
          city_id?: number | null
          created_at?: string
          data_completeness?: number | null
          data_quality_status?: string
          generated_at?: string
          id?: number
          max_validated_horizon_hours?: number | null
          method?: string
          model_version?: string
          pollutant?: string
          training_period_end?: string | null
          training_period_start?: string | null
          training_rows?: number | null
          validation_metrics?: Json
          ward_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "forecast_runs_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "city_config"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "forecast_runs_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      forecasts: {
        Row: {
          baseline_pred: number | null
          confidence: number | null
          forecast_run_id: number | null
          generated_at: string
          horizon_ts: string
          id: number
          local_excess: number | null
          lower_bound: number | null
          model_version: string | null
          pm25_pred: number | null
          pollutant: string
          predicted_value: number | null
          upper_bound: number | null
          ward_id: number
        }
        Insert: {
          baseline_pred?: number | null
          confidence?: number | null
          forecast_run_id?: number | null
          generated_at?: string
          horizon_ts: string
          id?: number
          local_excess?: number | null
          lower_bound?: number | null
          model_version?: string | null
          pm25_pred?: number | null
          pollutant?: string
          predicted_value?: number | null
          upper_bound?: number | null
          ward_id: number
        }
        Update: {
          baseline_pred?: number | null
          confidence?: number | null
          forecast_run_id?: number | null
          generated_at?: string
          horizon_ts?: string
          id?: number
          local_excess?: number | null
          lower_bound?: number | null
          model_version?: string | null
          pm25_pred?: number | null
          pollutant?: string
          predicted_value?: number | null
          upper_bound?: number | null
          ward_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "forecasts_forecast_run_id_fkey"
            columns: ["forecast_run_id"]
            isOneToOne: false
            referencedRelation: "forecast_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "forecasts_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      impact_evaluations: {
        Row: {
          action_id: number | null
          after_value: number | null
          before_value: number | null
          citizen_confirmed: boolean | null
          comparison_ward_id: number | null
          confidence: number | null
          created_at: string
          data_completeness: number | null
          evaluated_at: string
          evaluated_by: string | null
          expected_no_action_value: number | null
          id: number
          incident_id: number
          method: string
          method_limitation: string | null
          notes: string | null
          observation_window_hours: number | null
          outcome: Database["public"]["Enums"]["incident_outcome"]
          pct_change: number | null
          recurrence_window_days: number | null
          station_label: string | null
          weather_adjustment: Json | null
        }
        Insert: {
          action_id?: number | null
          after_value?: number | null
          before_value?: number | null
          citizen_confirmed?: boolean | null
          comparison_ward_id?: number | null
          confidence?: number | null
          created_at?: string
          data_completeness?: number | null
          evaluated_at?: string
          evaluated_by?: string | null
          expected_no_action_value?: number | null
          id?: number
          incident_id: number
          method: string
          method_limitation?: string | null
          notes?: string | null
          observation_window_hours?: number | null
          outcome?: Database["public"]["Enums"]["incident_outcome"]
          pct_change?: number | null
          recurrence_window_days?: number | null
          station_label?: string | null
          weather_adjustment?: Json | null
        }
        Update: {
          action_id?: number | null
          after_value?: number | null
          before_value?: number | null
          citizen_confirmed?: boolean | null
          comparison_ward_id?: number | null
          confidence?: number | null
          created_at?: string
          data_completeness?: number | null
          evaluated_at?: string
          evaluated_by?: string | null
          expected_no_action_value?: number | null
          id?: number
          incident_id?: number
          method?: string
          method_limitation?: string | null
          notes?: string | null
          observation_window_hours?: number | null
          outcome?: Database["public"]["Enums"]["incident_outcome"]
          pct_change?: number | null
          recurrence_window_days?: number | null
          station_label?: string | null
          weather_adjustment?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "impact_evaluations_action_id_fkey"
            columns: ["action_id"]
            isOneToOne: false
            referencedRelation: "actions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "impact_evaluations_comparison_ward_id_fkey"
            columns: ["comparison_ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "impact_evaluations_evaluated_by_fkey"
            columns: ["evaluated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "impact_evaluations_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
        ]
      }
      incident_events: {
        Row: {
          actor_id: string | null
          event_type: string
          id: number
          incident_id: number
          is_public: boolean
          note: string | null
          payload: Json | null
          ts: string
        }
        Insert: {
          actor_id?: string | null
          event_type: string
          id?: number
          incident_id: number
          is_public?: boolean
          note?: string | null
          payload?: Json | null
          ts?: string
        }
        Update: {
          actor_id?: string | null
          event_type?: string
          id?: number
          incident_id?: number
          is_public?: boolean
          note?: string | null
          payload?: Json | null
          ts?: string
        }
        Relationships: [
          {
            foreignKeyName: "incident_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incident_events_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
        ]
      }
      incident_evidence: {
        Row: {
          collected_at: string
          collected_by: string | null
          confidence: number | null
          created_at: string
          evidence_type: string
          id: number
          incident_id: number
          payload: Json
          reading_id: number | null
          report_id: number | null
          supports: boolean | null
        }
        Insert: {
          collected_at?: string
          collected_by?: string | null
          confidence?: number | null
          created_at?: string
          evidence_type: string
          id?: number
          incident_id: number
          payload?: Json
          reading_id?: number | null
          report_id?: number | null
          supports?: boolean | null
        }
        Update: {
          collected_at?: string
          collected_by?: string | null
          confidence?: number | null
          created_at?: string
          evidence_type?: string
          id?: number
          incident_id?: number
          payload?: Json
          reading_id?: number | null
          report_id?: number | null
          supports?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "incident_evidence_collected_by_fkey"
            columns: ["collected_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incident_evidence_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incident_evidence_reading_id_fkey"
            columns: ["reading_id"]
            isOneToOne: false
            referencedRelation: "readings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incident_evidence_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      incident_recurrence_reports: {
        Row: {
          created_at: string
          id: number
          incident_id: number
          lat: number | null
          lng: number | null
          note: string | null
          photo_url: string | null
          public_response: string | null
          recurrence_type: string
          reporter_id: string | null
          resulting_incident_id: number | null
          review_status: string
          reviewed_at: string | null
          reviewed_by: string | null
        }
        Insert: {
          created_at?: string
          id?: number
          incident_id: number
          lat?: number | null
          lng?: number | null
          note?: string | null
          photo_url?: string | null
          public_response?: string | null
          recurrence_type: string
          reporter_id?: string | null
          resulting_incident_id?: number | null
          review_status?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
        }
        Update: {
          created_at?: string
          id?: number
          incident_id?: number
          lat?: number | null
          lng?: number | null
          note?: string | null
          photo_url?: string | null
          public_response?: string | null
          recurrence_type?: string
          reporter_id?: string | null
          resulting_incident_id?: number | null
          review_status?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "incident_recurrence_reports_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incident_recurrence_reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incident_recurrence_reports_resulting_incident_id_fkey"
            columns: ["resulting_incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incident_recurrence_reports_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      incident_source_hypotheses: {
        Row: {
          computed_at: string
          confidence_level: Database["public"]["Enums"]["source_confidence_level"]
          contradicted_by: string | null
          contradicting_evidence: Json
          created_at: string
          data_quality_note: string | null
          evidence_scores: Json
          id: number
          incident_id: number
          is_current: boolean
          missing_evidence: Json
          model_version: string | null
          probability: number
          rationale: string | null
          review_note: string | null
          review_status: string
          reviewed_at: string | null
          reviewed_by: string | null
          source_category: Database["public"]["Enums"]["source_category"] | null
          supporting_evidence: Json
        }
        Insert: {
          computed_at?: string
          confidence_level?: Database["public"]["Enums"]["source_confidence_level"]
          contradicted_by?: string | null
          contradicting_evidence?: Json
          created_at?: string
          data_quality_note?: string | null
          evidence_scores?: Json
          id?: number
          incident_id: number
          is_current?: boolean
          missing_evidence?: Json
          model_version?: string | null
          probability: number
          rationale?: string | null
          review_note?: string | null
          review_status?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          source_category?:
            | Database["public"]["Enums"]["source_category"]
            | null
          supporting_evidence?: Json
        }
        Update: {
          computed_at?: string
          confidence_level?: Database["public"]["Enums"]["source_confidence_level"]
          contradicted_by?: string | null
          contradicting_evidence?: Json
          created_at?: string
          data_quality_note?: string | null
          evidence_scores?: Json
          id?: number
          incident_id?: number
          is_current?: boolean
          missing_evidence?: Json
          model_version?: string | null
          probability?: number
          rationale?: string | null
          review_note?: string | null
          review_status?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          source_category?:
            | Database["public"]["Enums"]["source_category"]
            | null
          supporting_evidence?: Json
        }
        Relationships: [
          {
            foreignKeyName: "incident_source_hypotheses_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incident_source_hypotheses_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      incidents: {
        Row: {
          assigned_authority: string | null
          city_id: number | null
          classification:
            | Database["public"]["Enums"]["incident_classification"]
            | null
          classification_note: string | null
          classification_set_by: string | null
          classification_source: string | null
          classification_updated_at: string | null
          closed_at: string | null
          created_at: string
          created_by: string | null
          detected_at: string
          detection_method: string
          detection_stage:
            | Database["public"]["Enums"]["incident_detection_stage"]
            | null
          id: number
          lat: number | null
          lng: number | null
          local_excess: number | null
          merged_into_incident_id: number | null
          primary_pollutant: string | null
          recurrence_of_incident_id: number | null
          severity: string | null
          source_confidence: Database["public"]["Enums"]["source_confidence_level"]
          status: Database["public"]["Enums"]["incident_status"]
          summary: string | null
          updated_at: string
          ward_id: number | null
        }
        Insert: {
          assigned_authority?: string | null
          city_id?: number | null
          classification?:
            | Database["public"]["Enums"]["incident_classification"]
            | null
          classification_note?: string | null
          classification_set_by?: string | null
          classification_source?: string | null
          classification_updated_at?: string | null
          closed_at?: string | null
          created_at?: string
          created_by?: string | null
          detected_at?: string
          detection_method: string
          detection_stage?:
            | Database["public"]["Enums"]["incident_detection_stage"]
            | null
          id?: number
          lat?: number | null
          lng?: number | null
          local_excess?: number | null
          merged_into_incident_id?: number | null
          primary_pollutant?: string | null
          recurrence_of_incident_id?: number | null
          severity?: string | null
          source_confidence?: Database["public"]["Enums"]["source_confidence_level"]
          status?: Database["public"]["Enums"]["incident_status"]
          summary?: string | null
          updated_at?: string
          ward_id?: number | null
        }
        Update: {
          assigned_authority?: string | null
          city_id?: number | null
          classification?:
            | Database["public"]["Enums"]["incident_classification"]
            | null
          classification_note?: string | null
          classification_set_by?: string | null
          classification_source?: string | null
          classification_updated_at?: string | null
          closed_at?: string | null
          created_at?: string
          created_by?: string | null
          detected_at?: string
          detection_method?: string
          detection_stage?:
            | Database["public"]["Enums"]["incident_detection_stage"]
            | null
          id?: number
          lat?: number | null
          lng?: number | null
          local_excess?: number | null
          merged_into_incident_id?: number | null
          primary_pollutant?: string | null
          recurrence_of_incident_id?: number | null
          severity?: string | null
          source_confidence?: Database["public"]["Enums"]["source_confidence_level"]
          status?: Database["public"]["Enums"]["incident_status"]
          summary?: string | null
          updated_at?: string
          ward_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "incidents_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "city_config"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incidents_classification_set_by_fkey"
            columns: ["classification_set_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incidents_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incidents_merged_into_incident_id_fkey"
            columns: ["merged_into_incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incidents_recurrence_of_incident_id_fkey"
            columns: ["recurrence_of_incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incidents_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      intervention_playbooks: {
        Row: {
          action_type: string
          approval_level: Database["public"]["Enums"]["approval_level"]
          checklist: Json
          city_id: number | null
          created_at: string
          estimated_cost: number | null
          estimated_cost_max: number | null
          estimated_cost_min: number | null
          estimated_minutes: number | null
          evidence_basis: string | null
          expected_duration_hours: number | null
          expected_effect: string | null
          expected_time_to_effect_hours: number | null
          for_regional: boolean
          id: number
          instructions: string | null
          is_active: boolean
          known_limitations: string | null
          min_evidence_level: Database["public"]["Enums"]["source_confidence_level"]
          recommended_pollutants: string[] | null
          required_equipment: string | null
          required_proof: string | null
          required_team: string | null
          responsible_agency_type: string | null
          slug: string | null
          source_category: Database["public"]["Enums"]["source_category"] | null
          title: string
          updated_at: string
          verification_method: string | null
          verification_window_hours: number | null
          version: number
        }
        Insert: {
          action_type?: string
          approval_level?: Database["public"]["Enums"]["approval_level"]
          checklist?: Json
          city_id?: number | null
          created_at?: string
          estimated_cost?: number | null
          estimated_cost_max?: number | null
          estimated_cost_min?: number | null
          estimated_minutes?: number | null
          evidence_basis?: string | null
          expected_duration_hours?: number | null
          expected_effect?: string | null
          expected_time_to_effect_hours?: number | null
          for_regional?: boolean
          id?: number
          instructions?: string | null
          is_active?: boolean
          known_limitations?: string | null
          min_evidence_level?: Database["public"]["Enums"]["source_confidence_level"]
          recommended_pollutants?: string[] | null
          required_equipment?: string | null
          required_proof?: string | null
          required_team?: string | null
          responsible_agency_type?: string | null
          slug?: string | null
          source_category?:
            | Database["public"]["Enums"]["source_category"]
            | null
          title: string
          updated_at?: string
          verification_method?: string | null
          verification_window_hours?: number | null
          version?: number
        }
        Update: {
          action_type?: string
          approval_level?: Database["public"]["Enums"]["approval_level"]
          checklist?: Json
          city_id?: number | null
          created_at?: string
          estimated_cost?: number | null
          estimated_cost_max?: number | null
          estimated_cost_min?: number | null
          estimated_minutes?: number | null
          evidence_basis?: string | null
          expected_duration_hours?: number | null
          expected_effect?: string | null
          expected_time_to_effect_hours?: number | null
          for_regional?: boolean
          id?: number
          instructions?: string | null
          is_active?: boolean
          known_limitations?: string | null
          min_evidence_level?: Database["public"]["Enums"]["source_confidence_level"]
          recommended_pollutants?: string[] | null
          required_equipment?: string | null
          required_proof?: string | null
          required_team?: string | null
          responsible_agency_type?: string | null
          slug?: string | null
          source_category?:
            | Database["public"]["Enums"]["source_category"]
            | null
          title?: string
          updated_at?: string
          verification_method?: string | null
          verification_window_hours?: number | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "intervention_playbooks_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "city_config"
            referencedColumns: ["id"]
          },
        ]
      }
      job_runs: {
        Row: {
          attempt: number
          city_code: string | null
          completed_at: string | null
          correlation_id: string
          created_at: string
          duration_ms: number | null
          error_category: string | null
          error_message: string | null
          id: number
          job_name: string
          rows_processed: number | null
          started_at: string
          status: string
        }
        Insert: {
          attempt?: number
          city_code?: string | null
          completed_at?: string | null
          correlation_id?: string
          created_at?: string
          duration_ms?: number | null
          error_category?: string | null
          error_message?: string | null
          id?: number
          job_name: string
          rows_processed?: number | null
          started_at?: string
          status?: string
        }
        Update: {
          attempt?: number
          city_code?: string | null
          completed_at?: string | null
          correlation_id?: string
          created_at?: string
          duration_ms?: number | null
          error_category?: string | null
          error_message?: string | null
          id?: number
          job_name?: string
          rows_processed?: number | null
          started_at?: string
          status?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          acknowledged_at: string | null
          channel: Database["public"]["Enums"]["notification_channel"]
          created_at: string
          delivered_at: string | null
          failure_reason: string | null
          id: number
          message_body: string
          recipient_contact: string | null
          recipient_id: string | null
          retry_count: number
          sent_at: string | null
          status: Database["public"]["Enums"]["notification_status"]
          task_dispatch_id: number | null
          template_key: string
        }
        Insert: {
          acknowledged_at?: string | null
          channel: Database["public"]["Enums"]["notification_channel"]
          created_at?: string
          delivered_at?: string | null
          failure_reason?: string | null
          id?: number
          message_body: string
          recipient_contact?: string | null
          recipient_id?: string | null
          retry_count?: number
          sent_at?: string | null
          status?: Database["public"]["Enums"]["notification_status"]
          task_dispatch_id?: number | null
          template_key: string
        }
        Update: {
          acknowledged_at?: string | null
          channel?: Database["public"]["Enums"]["notification_channel"]
          created_at?: string
          delivered_at?: string | null
          failure_reason?: string | null
          id?: number
          message_body?: string
          recipient_contact?: string | null
          recipient_id?: string | null
          retry_count?: number
          sent_at?: string | null
          status?: Database["public"]["Enums"]["notification_status"]
          task_dispatch_id?: number | null
          template_key?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_task_dispatch_id_fkey"
            columns: ["task_dispatch_id"]
            isOneToOne: false
            referencedRelation: "task_dispatches"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string | null
          full_name: string | null
          id: string
          lang: string | null
          phone: string | null
          role: Database["public"]["Enums"]["user_role"]
          ward_id: number | null
        }
        Insert: {
          created_at?: string | null
          full_name?: string | null
          id: string
          lang?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          ward_id?: number | null
        }
        Update: {
          created_at?: string | null
          full_name?: string | null
          id?: string
          lang?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          ward_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      readings: {
        Row: {
          aqi: number | null
          co: number | null
          id: number
          no2: number | null
          o3: number | null
          pm10: number | null
          pm25: number | null
          so2: number | null
          station_id: number
          ts: string
        }
        Insert: {
          aqi?: number | null
          co?: number | null
          id?: number
          no2?: number | null
          o3?: number | null
          pm10?: number | null
          pm25?: number | null
          so2?: number | null
          station_id: number
          ts: string
        }
        Update: {
          aqi?: number | null
          co?: number | null
          id?: number
          no2?: number | null
          o3?: number | null
          pm10?: number | null
          pm25?: number | null
          so2?: number | null
          station_id?: number
          ts?: string
        }
        Relationships: [
          {
            foreignKeyName: "readings_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
        ]
      }
      report_events: {
        Row: {
          actor_id: string | null
          id: number
          note: string | null
          report_id: number
          status: Database["public"]["Enums"]["report_status"]
          ts: string
        }
        Insert: {
          actor_id?: string | null
          id?: number
          note?: string | null
          report_id: number
          status: Database["public"]["Enums"]["report_status"]
          ts?: string
        }
        Update: {
          actor_id?: string | null
          id?: number
          note?: string | null
          report_id?: number
          status?: Database["public"]["Enums"]["report_status"]
          ts?: string
        }
        Relationships: [
          {
            foreignKeyName: "report_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "report_events_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          ai_category: Database["public"]["Enums"]["source_category"] | null
          ai_meta: Json | null
          created_at: string | null
          description: string | null
          id: number
          incident_id: number | null
          lat: number | null
          lng: number | null
          photo_url: string | null
          reporter_id: string | null
          status: Database["public"]["Enums"]["report_status"]
          ward_id: number | null
        }
        Insert: {
          ai_category?: Database["public"]["Enums"]["source_category"] | null
          ai_meta?: Json | null
          created_at?: string | null
          description?: string | null
          id?: number
          incident_id?: number | null
          lat?: number | null
          lng?: number | null
          photo_url?: string | null
          reporter_id?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          ward_id?: number | null
        }
        Update: {
          ai_category?: Database["public"]["Enums"]["source_category"] | null
          ai_meta?: Json | null
          created_at?: string | null
          description?: string | null
          id?: number
          incident_id?: number | null
          lat?: number | null
          lng?: number | null
          photo_url?: string | null
          reporter_id?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          ward_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "reports_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      responsibility_registry: {
        Row: {
          asset_description: string | null
          backup_agency: string | null
          backup_officer: string | null
          backup_team: string | null
          city_id: number | null
          contact_channel: Json
          created_at: string
          division_zone: string | null
          escalation_contact: string | null
          escalation_hierarchy: Json
          id: number
          is_active: boolean
          is_disputed: boolean
          mapping_confidence: string
          mapping_source: string | null
          owner_name: string | null
          regulating_authority: string | null
          responsible_officer: string | null
          source_category: Database["public"]["Enums"]["source_category"] | null
          supported_intervention_types: string[]
          team_name: string | null
          updated_at: string
          ward_id: number | null
          working_hours: Json | null
          zone_description: string | null
        }
        Insert: {
          asset_description?: string | null
          backup_agency?: string | null
          backup_officer?: string | null
          backup_team?: string | null
          city_id?: number | null
          contact_channel?: Json
          created_at?: string
          division_zone?: string | null
          escalation_contact?: string | null
          escalation_hierarchy?: Json
          id?: number
          is_active?: boolean
          is_disputed?: boolean
          mapping_confidence?: string
          mapping_source?: string | null
          owner_name?: string | null
          regulating_authority?: string | null
          responsible_officer?: string | null
          source_category?:
            | Database["public"]["Enums"]["source_category"]
            | null
          supported_intervention_types?: string[]
          team_name?: string | null
          updated_at?: string
          ward_id?: number | null
          working_hours?: Json | null
          zone_description?: string | null
        }
        Update: {
          asset_description?: string | null
          backup_agency?: string | null
          backup_officer?: string | null
          backup_team?: string | null
          city_id?: number | null
          contact_channel?: Json
          created_at?: string
          division_zone?: string | null
          escalation_contact?: string | null
          escalation_hierarchy?: Json
          id?: number
          is_active?: boolean
          is_disputed?: boolean
          mapping_confidence?: string
          mapping_source?: string | null
          owner_name?: string | null
          regulating_authority?: string | null
          responsible_officer?: string | null
          source_category?:
            | Database["public"]["Enums"]["source_category"]
            | null
          supported_intervention_types?: string[]
          team_name?: string | null
          updated_at?: string
          ward_id?: number | null
          working_hours?: Json | null
          zone_description?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "responsibility_registry_backup_officer_fkey"
            columns: ["backup_officer"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "responsibility_registry_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "city_config"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "responsibility_registry_responsible_officer_fkey"
            columns: ["responsible_officer"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "responsibility_registry_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      sla_rules: {
        Row: {
          accept_hours: number
          ack_hours: number
          action_type: string | null
          agency: string | null
          arrival_hours: number
          city_id: number | null
          completion_hours: number
          created_at: string
          evidence_level:
            | Database["public"]["Enums"]["source_confidence_level"]
            | null
          id: number
          is_active: boolean
          priority: number
          severity: string | null
          slug: string | null
          source_category: Database["public"]["Enums"]["source_category"] | null
          time_of_day: string | null
          verification_hours: number
        }
        Insert: {
          accept_hours?: number
          ack_hours?: number
          action_type?: string | null
          agency?: string | null
          arrival_hours?: number
          city_id?: number | null
          completion_hours?: number
          created_at?: string
          evidence_level?:
            | Database["public"]["Enums"]["source_confidence_level"]
            | null
          id?: number
          is_active?: boolean
          priority?: number
          severity?: string | null
          slug?: string | null
          source_category?:
            | Database["public"]["Enums"]["source_category"]
            | null
          time_of_day?: string | null
          verification_hours?: number
        }
        Update: {
          accept_hours?: number
          ack_hours?: number
          action_type?: string | null
          agency?: string | null
          arrival_hours?: number
          city_id?: number | null
          completion_hours?: number
          created_at?: string
          evidence_level?:
            | Database["public"]["Enums"]["source_confidence_level"]
            | null
          id?: number
          is_active?: boolean
          priority?: number
          severity?: string | null
          slug?: string | null
          source_category?:
            | Database["public"]["Enums"]["source_category"]
            | null
          time_of_day?: string | null
          verification_hours?: number
        }
        Relationships: [
          {
            foreignKeyName: "sla_rules_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "city_config"
            referencedColumns: ["id"]
          },
        ]
      }
      stations: {
        Row: {
          created_at: string | null
          external_ref: string | null
          id: number
          is_active: boolean
          lat: number | null
          lng: number | null
          name: string
          sensor_type: string
          source: string | null
          ward_id: number | null
        }
        Insert: {
          created_at?: string | null
          external_ref?: string | null
          id?: number
          is_active?: boolean
          lat?: number | null
          lng?: number | null
          name: string
          sensor_type?: string
          source?: string | null
          ward_id?: number | null
        }
        Update: {
          created_at?: string | null
          external_ref?: string | null
          id?: number
          is_active?: boolean
          lat?: number | null
          lng?: number | null
          name?: string
          sensor_type?: string
          source?: string | null
          ward_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "stations_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      t_ids: {
        Row: {
          k: string
          v: number | null
        }
        Insert: {
          k: string
          v?: number | null
        }
        Update: {
          k?: string
          v?: number | null
        }
        Relationships: []
      }
      task_dispatches: {
        Row: {
          accepted_at: string | null
          acknowledged_at: string | null
          action_id: number
          approved_at: string | null
          approved_by: string | null
          arrived_at: string | null
          asset_description: string | null
          backup_agency: string | null
          backup_team: string | null
          cancellation_reason: string | null
          city_id: number | null
          completed_at: string | null
          created_at: string
          created_by: string | null
          dispute_resolution_note: string | null
          division_zone: string | null
          escalated_at: string | null
          escalation_level: number
          escalation_reason: string | null
          id: number
          incident_id: number | null
          is_current: boolean
          physical_location: string | null
          primary_officer: string | null
          primary_team: string | null
          registry_id: number | null
          rejection_reason: string | null
          requires_approval: boolean
          reroute_reason: string | null
          resource_availability: string
          resource_note: string | null
          responsible_agency: string | null
          routed_at: string | null
          routing_confidence: Database["public"]["Enums"]["routing_confidence_level"]
          routing_evidence: Json
          sent_at: string | null
          sla_accept_due_at: string | null
          sla_ack_due_at: string | null
          sla_arrival_due_at: string | null
          sla_completion_due_at: string | null
          sla_verification_due_at: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["task_dispatch_status"]
          superseded_by_dispatch_id: number | null
          updated_at: string
          verification_requested_at: string | null
          verified_at: string | null
          ward_id: number | null
        }
        Insert: {
          accepted_at?: string | null
          acknowledged_at?: string | null
          action_id: number
          approved_at?: string | null
          approved_by?: string | null
          arrived_at?: string | null
          asset_description?: string | null
          backup_agency?: string | null
          backup_team?: string | null
          cancellation_reason?: string | null
          city_id?: number | null
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          dispute_resolution_note?: string | null
          division_zone?: string | null
          escalated_at?: string | null
          escalation_level?: number
          escalation_reason?: string | null
          id?: number
          incident_id?: number | null
          is_current?: boolean
          physical_location?: string | null
          primary_officer?: string | null
          primary_team?: string | null
          registry_id?: number | null
          rejection_reason?: string | null
          requires_approval?: boolean
          reroute_reason?: string | null
          resource_availability?: string
          resource_note?: string | null
          responsible_agency?: string | null
          routed_at?: string | null
          routing_confidence?: Database["public"]["Enums"]["routing_confidence_level"]
          routing_evidence?: Json
          sent_at?: string | null
          sla_accept_due_at?: string | null
          sla_ack_due_at?: string | null
          sla_arrival_due_at?: string | null
          sla_completion_due_at?: string | null
          sla_verification_due_at?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["task_dispatch_status"]
          superseded_by_dispatch_id?: number | null
          updated_at?: string
          verification_requested_at?: string | null
          verified_at?: string | null
          ward_id?: number | null
        }
        Update: {
          accepted_at?: string | null
          acknowledged_at?: string | null
          action_id?: number
          approved_at?: string | null
          approved_by?: string | null
          arrived_at?: string | null
          asset_description?: string | null
          backup_agency?: string | null
          backup_team?: string | null
          cancellation_reason?: string | null
          city_id?: number | null
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          dispute_resolution_note?: string | null
          division_zone?: string | null
          escalated_at?: string | null
          escalation_level?: number
          escalation_reason?: string | null
          id?: number
          incident_id?: number | null
          is_current?: boolean
          physical_location?: string | null
          primary_officer?: string | null
          primary_team?: string | null
          registry_id?: number | null
          rejection_reason?: string | null
          requires_approval?: boolean
          reroute_reason?: string | null
          resource_availability?: string
          resource_note?: string | null
          responsible_agency?: string | null
          routed_at?: string | null
          routing_confidence?: Database["public"]["Enums"]["routing_confidence_level"]
          routing_evidence?: Json
          sent_at?: string | null
          sla_accept_due_at?: string | null
          sla_ack_due_at?: string | null
          sla_arrival_due_at?: string | null
          sla_completion_due_at?: string | null
          sla_verification_due_at?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["task_dispatch_status"]
          superseded_by_dispatch_id?: number | null
          updated_at?: string
          verification_requested_at?: string | null
          verified_at?: string | null
          ward_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "task_dispatches_action_id_fkey"
            columns: ["action_id"]
            isOneToOne: false
            referencedRelation: "actions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dispatches_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dispatches_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "city_config"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dispatches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dispatches_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dispatches_primary_officer_fkey"
            columns: ["primary_officer"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dispatches_registry_id_fkey"
            columns: ["registry_id"]
            isOneToOne: false
            referencedRelation: "responsibility_registry"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dispatches_superseded_by_dispatch_id_fkey"
            columns: ["superseded_by_dispatch_id"]
            isOneToOne: false
            referencedRelation: "task_dispatches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dispatches_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
      wards: {
        Row: {
          boundary: Json | null
          city_id: number | null
          created_at: string | null
          deputy_commissioner: string | null
          dominant_source: Database["public"]["Enums"]["source_category"] | null
          id: number
          is_hotspot: boolean
          lat: number | null
          lng: number | null
          name: string
        }
        Insert: {
          boundary?: Json | null
          city_id?: number | null
          created_at?: string | null
          deputy_commissioner?: string | null
          dominant_source?:
            | Database["public"]["Enums"]["source_category"]
            | null
          id?: number
          is_hotspot?: boolean
          lat?: number | null
          lng?: number | null
          name: string
        }
        Update: {
          boundary?: Json | null
          city_id?: number | null
          created_at?: string | null
          deputy_commissioner?: string | null
          dominant_source?:
            | Database["public"]["Enums"]["source_category"]
            | null
          id?: number
          is_hotspot?: boolean
          lat?: number | null
          lng?: number | null
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "wards_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "city_config"
            referencedColumns: ["id"]
          },
        ]
      }
      weather: {
        Row: {
          humidity: number | null
          id: number
          precipitation: number | null
          pressure: number | null
          temp_c: number | null
          ts: string
          ward_id: number
          wind_dir: number | null
          wind_speed: number | null
        }
        Insert: {
          humidity?: number | null
          id?: number
          precipitation?: number | null
          pressure?: number | null
          temp_c?: number | null
          ts: string
          ward_id: number
          wind_dir?: number | null
          wind_speed?: number | null
        }
        Update: {
          humidity?: number | null
          id?: number
          precipitation?: number | null
          pressure?: number | null
          temp_c?: number | null
          ts?: string
          ward_id?: number
          wind_dir?: number | null
          wind_speed?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "weather_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "wards"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _e2e_city: { Args: { p_prefix: string }; Returns: number }
      _resolve_task_routing: {
        Args: { p_action_id: number }
        Returns: {
          asset_description: string
          backup_agency: string
          backup_team: string
          division_zone: string
          physical_location: string
          primary_officer: string
          primary_team: string
          registry_id: number
          responsible_agency: string
          routing_confidence: Database["public"]["Enums"]["routing_confidence_level"]
          routing_evidence: Json
        }[]
      }
      _send_task_notification: {
        Args: {
          p_dispatch_id: number
          p_message: string
          p_recipient: string
          p_template: string
        }
        Returns: undefined
      }
      _t100_action: {
        Args: { p_incident: number; p_type?: string; p_ward: number }
        Returns: number
      }
      _t100_setup: {
        Args: { p_officer?: string; p_prefix: string }
        Returns: {
          city_id: number
          incident_id: number
          ward_id: number
        }[]
      }
      _t110_action: {
        Args: { p_incident: number; p_type?: string; p_ward: number }
        Returns: number
      }
      _t110_setup: {
        Args: { p_officer?: string; p_prefix: string }
        Returns: {
          city_id: number
          incident_id: number
          ward_id: number
        }[]
      }
      as_service: { Args: never; Returns: undefined }
      as_user: { Args: { p: string }; Returns: undefined }
      auth_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      auth_ward: { Args: never; Returns: number }
      calculate_incident_source_attribution: {
        Args: { p_force?: boolean; p_incident_id: number }
        Returns: undefined
      }
      city_feature_enabled: {
        Args: { p_city_id: number; p_default?: boolean; p_flag: string }
        Returns: boolean
      }
      complete_job_run: {
        Args: { p_rows_processed?: number; p_run_id: number }
        Returns: undefined
      }
      dispatch_intervention_task: {
        Args: { p_action_id: number; p_actor_id: string }
        Returns: number
      }
      escalate_stale_task_dispatches: {
        Args: { p_city_code?: string }
        Returns: {
          dispatch_id: number
          new_status: Database["public"]["Enums"]["task_dispatch_status"]
        }[]
      }
      evaluate_station_pollutant_anomaly: {
        Args: { p_pollutant: string; p_station_id: number }
        Returns: number
      }
      fail_job_run: {
        Args: {
          p_error_category?: string
          p_error_message: string
          p_run_id: number
        }
        Returns: undefined
      }
      get_incident_responsible_authority: {
        Args: { p_incident_id: number }
        Returns: {
          asset_description: string
          escalation_contact: string
          is_disputed: boolean
          match_basis: string
          note: string
          owner_name: string
          regulating_authority: string
          routing_confidence: number
          source_category: Database["public"]["Enums"]["source_category"]
        }[]
      }
      link_report_to_incident: {
        Args: {
          p_radius_m?: number
          p_recency_hours?: number
          p_report_id: number
        }
        Returns: number
      }
      list_assignable_officers: {
        Args: { p_ward_id?: number }
        Returns: {
          full_name: string
          id: string
          ward_id: number
        }[]
      }
      list_my_citizen_missions: {
        Args: never
        Returns: {
          incident_id: number
          incident_status: Database["public"]["Enums"]["incident_status"]
          leading_category: Database["public"]["Enums"]["source_category"]
          mission_id: number
          mission_type: string
          outcome: string
          public_prompt: string
          severity: string
          status: Database["public"]["Enums"]["mission_status"]
          ward_name: string
        }[]
      }
      list_my_recurrence_reports: {
        Args: { p_incident_id: number }
        Returns: {
          created_at: string
          outcome_kind: string
          public_response: string
          recurrence_type: string
          report_id: number
          review_status: string
        }[]
      }
      mkreport: {
        Args: {
          p_cat: string
          p_desc: string
          p_lat: number
          p_lng: number
          p_user: string
        }
        Returns: number
      }
      preview_task_routing: {
        Args: { p_action_id: number }
        Returns: {
          asset_description: string
          backup_agency: string
          backup_team: string
          division_zone: string
          physical_location: string
          primary_officer: string
          primary_team: string
          registry_id: number
          responsible_agency: string
          routing_confidence: Database["public"]["Enums"]["routing_confidence_level"]
          routing_evidence: Json
        }[]
      }
      record_impact_evaluation: {
        Args: {
          p_action_id: number
          p_after: number
          p_before: number
          p_completeness: number
          p_incident_id: number
          p_notes?: string
          p_station: string
          p_window_hours: number
        }
        Returns: string
      }
      report_resource_unavailable: {
        Args: { p_actor_id: string; p_dispatch_id: number; p_note: string }
        Returns: undefined
      }
      request_task_reroute: {
        Args: { p_actor_id: string; p_dispatch_id: number; p_reason: string }
        Returns: undefined
      }
      resolve_jurisdiction_dispute: {
        Args: {
          p_actor_id: string
          p_dispatch_id: number
          p_note: string
          p_registry_id: number
        }
        Returns: undefined
      }
      run_anomaly_detection: {
        Args: { p_city_code?: string }
        Returns: {
          candidate_id: number
          pollutant: string
          station_id: number
        }[]
      }
      run_incident_source_attribution: {
        Args: { p_city_code?: string; p_force?: boolean }
        Returns: {
          incident_id: number
        }[]
      }
      set_station_active: {
        Args: { p_actor_id: string; p_is_active: boolean; p_station_id: number }
        Returns: undefined
      }
      start_job_run: {
        Args: { p_attempt?: number; p_city_code?: string; p_job_name: string }
        Returns: number
      }
      submit_citizen_action_verification: {
        Args: { p_answer: string; p_incident_id: number }
        Returns: undefined
      }
      submit_citizen_verification: {
        Args: { p_mission_id: number; p_outcome: string }
        Returns: undefined
      }
      submit_incident_recurrence_report: {
        Args: {
          p_incident_id: number
          p_lat?: number
          p_lng?: number
          p_note?: string
          p_photo_url?: string
          p_recurrence_type: string
        }
        Returns: number
      }
      system_health_summary: {
        Args: never
        Returns: {
          city_code: string
          is_stale: boolean
          job_name: string
          last_completed_at: string
          last_error_message: string
          last_started_at: string
          last_status: string
        }[]
      }
      transition_task_dispatch: {
        Args: {
          p_actor_id: string
          p_dispatch_id: number
          p_new_status: Database["public"]["Enums"]["task_dispatch_status"]
          p_reason?: string
        }
        Returns: undefined
      }
    }
    Enums: {
      action_workflow_status:
        | "drafted"
        | "awaiting_approval"
        | "assigned"
        | "accepted"
        | "in_progress"
        | "completed"
        | "verification_pending"
        | "effective"
        | "partly_effective"
        | "ineffective"
        | "inconclusive"
        | "reopened"
      approval_level: "automatic" | "command" | "authorised_legal"
      incident_classification: "local" | "mixed" | "regional" | "uncertain"
      incident_detection_stage: "predicted" | "detected" | "confirmed"
      incident_outcome:
        | "effective"
        | "partly_effective"
        | "ineffective"
        | "inconclusive"
        | "source_disproved"
        | "completed_no_change"
        | "recurred"
      incident_status:
        | "detected"
        | "under_review"
        | "evidence_gathering"
        | "routed"
        | "action_approved"
        | "action_dispatched"
        | "in_progress"
        | "verifying"
        | "closed"
      mission_status:
        | "proposed"
        | "dispatched"
        | "in_progress"
        | "completed"
        | "cancelled"
      notification_channel: "in_app" | "email" | "sms" | "whatsapp"
      notification_status:
        | "pending"
        | "sent"
        | "delivered"
        | "failed"
        | "acknowledged"
      report_status:
        | "submitted"
        | "verified"
        | "assigned"
        | "acted"
        | "resolved"
        | "rejected"
      routing_confidence_level:
        | "confirmed"
        | "probable"
        | "disputed"
        | "unresolved"
      source_category:
        | "construction_dust"
        | "road_dust"
        | "open_burning"
        | "industrial"
        | "vehicular"
        | "waste"
        | "other"
        | "regional_transport"
        | "mixed"
        | "unresolved"
      source_confidence_level:
        | "suspected"
        | "corroborated"
        | "officially_verified"
      task_dispatch_status:
        | "drafted"
        | "awaiting_approval"
        | "approved"
        | "routed"
        | "sent"
        | "acknowledged"
        | "accepted"
        | "in_progress"
        | "completed"
        | "verification_pending"
        | "overdue"
        | "escalated"
        | "rejected"
        | "rerouted"
        | "cancelled"
      user_role: "citizen" | "field_officer" | "commander" | "admin"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      action_workflow_status: [
        "drafted",
        "awaiting_approval",
        "assigned",
        "accepted",
        "in_progress",
        "completed",
        "verification_pending",
        "effective",
        "partly_effective",
        "ineffective",
        "inconclusive",
        "reopened",
      ],
      approval_level: ["automatic", "command", "authorised_legal"],
      incident_classification: ["local", "mixed", "regional", "uncertain"],
      incident_detection_stage: ["predicted", "detected", "confirmed"],
      incident_outcome: [
        "effective",
        "partly_effective",
        "ineffective",
        "inconclusive",
        "source_disproved",
        "completed_no_change",
        "recurred",
      ],
      incident_status: [
        "detected",
        "under_review",
        "evidence_gathering",
        "routed",
        "action_approved",
        "action_dispatched",
        "in_progress",
        "verifying",
        "closed",
      ],
      mission_status: [
        "proposed",
        "dispatched",
        "in_progress",
        "completed",
        "cancelled",
      ],
      notification_channel: ["in_app", "email", "sms", "whatsapp"],
      notification_status: [
        "pending",
        "sent",
        "delivered",
        "failed",
        "acknowledged",
      ],
      report_status: [
        "submitted",
        "verified",
        "assigned",
        "acted",
        "resolved",
        "rejected",
      ],
      routing_confidence_level: [
        "confirmed",
        "probable",
        "disputed",
        "unresolved",
      ],
      source_category: [
        "construction_dust",
        "road_dust",
        "open_burning",
        "industrial",
        "vehicular",
        "waste",
        "other",
        "regional_transport",
        "mixed",
        "unresolved",
      ],
      source_confidence_level: [
        "suspected",
        "corroborated",
        "officially_verified",
      ],
      task_dispatch_status: [
        "drafted",
        "awaiting_approval",
        "approved",
        "routed",
        "sent",
        "acknowledged",
        "accepted",
        "in_progress",
        "completed",
        "verification_pending",
        "overdue",
        "escalated",
        "rejected",
        "rerouted",
        "cancelled",
      ],
      user_role: ["citizen", "field_officer", "commander", "admin"],
    },
  },
} as const

