#!/usr/bin/env python3
"""Honest forecast-validation + predicted-incident report.

Reads the live `forecast_runs`, `incidents` and `anomaly_candidates` tables
(READ ONLY - never writes, never touches forecast.py or the model) and
answers the two questions that actually matter for this project's pitch:

1. How often does the trained LightGBM model genuinely beat the BEST of four
   naive baselines (persistence, diurnal, same-hour-yesterday, rolling-24h)?
   This is exactly the follow-up docs/data/forecast-baseline-gate-upgrade.md
   §9 asks for - the real validated-rate under the stronger gate, not a
   single dry-run snapshot.
2. Where did the system PREDICT a threshold crossing before it happened
   (predicted-stage incidents) - the "we saw it coming" evidence.

Writes a regenerable markdown report to docs/data/forecast-validation-report.md
and prints a summary. Run it any time to refresh the numbers:

    python scripts/forecast_validation_report.py
"""
from __future__ import annotations

import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import config  # noqa: E402
from supabase import create_client  # noqa: E402

HORIZONS = ("6", "12", "24", "48")
BASELINE_LABELS = {
    "persistence": "Persistence (last value)",
    "diurnal": "Diurnal (hour-of-day mean)",
    "same_hour_yesterday": "Same-hour-yesterday",
    "rolling_24h_avg": "Rolling 24h average",
}
REPORT_PATH = Path(__file__).resolve().parent.parent.parent / "docs" / "data" / "forecast-validation-report.md"


def sb():
    return create_client(config.SUPABASE_URL, config.SUPABASE_SERVICE_ROLE_KEY)


def latest_runs_per_pair(client) -> dict:
    """Newest forecast_run per (ward_id, pollutant)."""
    rows = (
        client.table("forecast_runs")
        .select("ward_id,pollutant,method,training_rows,beats_persistence,"
                "max_validated_horizon_hours,data_quality_status,validation_metrics,generated_at")
        .order("generated_at", desc=True)
        .limit(1000)
        .execute()
        .data
    )
    seen: dict = {}
    for r in rows:
        seen.setdefault((r["ward_id"], r["pollutant"]), r)
    return seen


def build_report() -> str:
    client = sb()
    wd = {w["id"]: w["name"] for w in client.table("wards").select("id,name").execute().data}
    pairs = latest_runs_per_pair(client)

    total = len(pairs)
    validated = [r for r in pairs.values() if r["beats_persistence"]]
    lgb = [r for r in pairs.values() if r["method"] == "lightgbm"]
    method_counts = Counter(r["method"] for r in pairs.values())

    # which baseline is strongest, tallied across every pair x horizon
    baseline_tally: Counter = Counter()
    for r in pairs.values():
        vm = r.get("validation_metrics") or {}
        for h in HORIZONS:
            m = vm.get(h)
            if m and m.get("best_baseline"):
                baseline_tally[m["best_baseline"]] += 1
    baseline_total = sum(baseline_tally.values()) or 1

    # per-pollutant validated rate
    by_pollutant: dict = {}
    for (wid, pol), r in pairs.items():
        d = by_pollutant.setdefault(pol, {"total": 0, "validated": 0})
        d["total"] += 1
        if r["beats_persistence"]:
            d["validated"] += 1

    # predicted-stage incidents joined to their anomaly candidate
    preds = (
        client.table("incidents")
        .select("id,ward_id,detection_stage,detection_method,primary_pollutant,status,detected_at,local_excess")
        .eq("detection_stage", "predicted")
        .execute()
        .data
    )
    cand_by_incident: dict = {}
    if preds:
        cands = (
            client.table("anomaly_candidates")
            .select("incident_id,projected_crossing_at,threshold_crossing_probability,"
                    "rate_of_increase,confidence,threshold_used,prediction_method")
            .in_("incident_id", [p["id"] for p in preds])
            .execute()
            .data
        )
        for c in cands:
            cand_by_incident.setdefault(c["incident_id"], c)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    L = []
    L.append("# Forecast Validation & Predicted-Incident Report")
    L.append("")
    L.append(f"_Auto-generated by `ingest/scripts/forecast_validation_report.py` - {now}. "
             "Read-only over `forecast_runs` / `incidents` / `anomaly_candidates`; regenerate any time._")
    L.append("")
    L.append("## 1. Forecast validation (honest, under the best-of-4-baseline gate)")
    L.append("")
    L.append("`beats_persistence` here means the LightGBM model beat the **strongest of four** "
             "baselines (persistence, diurnal, same-hour-yesterday, rolling-24h), per "
             "`docs/data/forecast-baseline-gate-upgrade.md` - a deliberately hard, honest bar.")
    L.append("")
    rate = 100.0 * len(validated) / total if total else 0.0
    L.append(f"- Ward+pollutant pairs evaluated: **{total}**")
    L.append(f"- Pairs where LightGBM clears the gate: **{len(validated)} ({rate:.0f}%)**")
    L.append(f"- Method actually served: " + ", ".join(f"{k} {v}" for k, v in method_counts.items()))
    L.append("")
    L.append("### Per-pollutant validated rate")
    L.append("")
    L.append("| Pollutant | Validated / total |")
    L.append("|---|---|")
    for pol, d in sorted(by_pollutant.items()):
        L.append(f"| {pol} | {d['validated']} / {d['total']} |")
    L.append("")
    L.append("### Which baseline is actually strongest (across all pairs × horizons)")
    L.append("")
    L.append("The whole point of the stronger gate: persistence is rarely the real opponent.")
    L.append("")
    L.append("| Baseline | Times strongest | Share |")
    L.append("|---|---|---|")
    for b, n in baseline_tally.most_common():
        L.append(f"| {BASELINE_LABELS.get(b, b)} | {n} | {100.0*n/baseline_total:.0f}% |")
    L.append("")
    if lgb:
        L.append("### Where LightGBM genuinely wins")
        L.append("")
        L.append("| Ward | Pollutant | Validated to | Train rows |")
        L.append("|---|---|---|---|")
        for r in sorted(lgb, key=lambda x: -(x["max_validated_horizon_hours"] or 0)):
            L.append(f"| {wd.get(r['ward_id'],'?')} | {r['pollutant']} | "
                     f"{r['max_validated_horizon_hours']}h | {r['training_rows']} |")
        L.append("")
    else:
        L.append("_No ward+pollutant pair currently clears the best-of-4 gate at this snapshot - "
                 "the honest result: simple baselines are competitive for local-excess here._")
        L.append("")

    L.append("## 2. Predicted incidents - 'we saw it coming'")
    L.append("")
    if not preds:
        L.append("_No predicted-stage incidents at this snapshot._")
    else:
        L.append(f"The detection engine created **{len(preds)}** predicted-stage incidents "
                 "(a threshold crossing projected from real readings/forecast, before it happened):")
        L.append("")
        L.append("| Incident | Ward | Pollutant | Local excess | Projected crossing | Prob. | Method |")
        L.append("|---|---|---|---|---|---|---|")
        for p in sorted(preds, key=lambda x: str(x["detected_at"]), reverse=True):
            c = cand_by_incident.get(p["id"], {})
            cross = c.get("projected_crossing_at") or "-"
            prob = c.get("threshold_crossing_probability")
            prob_s = f"{prob:.0%}" if isinstance(prob, (int, float)) else "-"
            le = p.get("local_excess")
            le_s = f"+{le:.0f}" if isinstance(le, (int, float)) else "-"
            method = c.get("prediction_method") or p.get("detection_method") or "-"
            L.append(f"| #{p['id']} | {wd.get(p['ward_id'],'?')} | {p['primary_pollutant']} | "
                     f"{le_s} | {str(cross)[:16]} | {prob_s} | {method} |")
        L.append("")

    L.append("## 3. How to read this for the pitch")
    L.append("")
    L.append("- The forecasting story is **honesty**, not a magic model: we validate against four "
             "baselines and only promote ML where it genuinely wins. That is a credibility feature.")
    L.append("- The **prediction value is at the incident level** - the system flags a probable "
             "threshold crossing before it happens, which is what drives earlier action (the Gati metric).")
    L.append("")
    return "\n".join(L)


def main() -> int:
    report = build_report()
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(report)
    print(f"\n[written] {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
